apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-analytics
  namespace: vitas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-analytics
  template:
    metadata:
      labels:
        app: web-analytics
    spec:
      containers:
        - name: web
          image: python:3.11-slim
          command:
            - python
            - "-c"
            - |
              import http.server, socketserver
              class H(http.server.SimpleHTTPRequestHandler):
                  def do_GET(self):
                      self.send_response(200)
                      self.end_headers()
                      self.wfile.write(b'GitOps WORKS v2')
              socketserver.TCPServer(('',5000),H).serve_forever()
          ports:
            - containerPort: 5000
