apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: vitas-app
spec:
  selector:
    app: web-analytics
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
  type: NodePort